name: Create PR in Composites

on:
  pull_request:
    branches: ['main']
  workflow_dispatch: {}

jobs:    
  Create-PR-in-CompositeA:
    runs-on: ubuntu-22.04    
    timeout-minutes: 15
    steps:
      - name: Print GitHub Environment
        run: echo '${{ toJSON(github) }}'
      - name: Print Environment Variables
        run: env | sort
      - name: Checkout CompositeA
        uses: actions/checkout@v2
        with:
          repository: 'opensafety/compositeA'
          ref: 'main'                            #This should be all the branches which include 'main' of componentA
          submodules: 'false'
      - name: 'Bump ComponentA in CompositeA'
        env:
          NEW_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          set -x -e -o pipefail
          exec 2>&1
          git submodule init
          git remote -v
          git config -l
          cd components/componentA
          git init
          git remote add origin https://github.com/opensafety/componentA.git
          git fetch --depth=1 origin ${NEW_SHA}
          git reset ${NEW_SHA}
          cd ${GITHUB_WORKSPACE}
          git status
      - name: Create Pull Request In CompositeA
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Bump ${{ github.event.pull_request.base.repo.name }} to PR ${{ github.pul_request.number }}"
          branch: component-pr/main/${{ github.event.pull_request.base.repo.owner.login }}/${{ github.event.pull_request.base.repo.name }}/${{ github.event.pull_request.number }}
          title: "PR ${{ github.event.pull_request.base.repo.name }}#${{ github.event.pull_request.number }}"
          body: |
            ${{ github.event.pull_request.head.sha }}
            ${{ github.event.pull_request.html_url }}
            <pre>
            ======== Title =======
            "${{ github.event.pull_request.title }}"
            ======== Body ========
            ${{ github.event.pull_request.body }}
            ======================
            </pre>
          token: ${{ secrets.ORG_PAT }}
          add-paths: |
            components/componentA
