name: Create PR in Composites

on:
  merge_group:
    types:
      - checks_requested
      - destroyed
    branches:
      - main

jobs:    
  Create-PR-in-CompositeA:
    runs-on: ubuntu-22.04    
    timeout-minutes: 15
    if: github.event_name == 'merge_group'
    steps:
      - name: Print GitHub Environment
        run: echo '${{ toJSON(github) }}'
      - name: Print Environment Variables
        run: env | sort
      - name: Checkout CompositeA
        uses: actions/checkout@v2
        with:
          repository: 'opensafety/compositeA'
          ref: 'main'                            #This should be all the branches which include 'main' of componentA
          submodules: 'false'
      - name: 'Bump ComponentA in CompositeA'
        env:
          NEW_SHA: ${{ github.sha }}
        run: |
          set -x -e -o pipefail
          exec 2>&1
          git submodule init
          git remote -v
          git config -l
          cd components/componentA
          git init
          git remote add origin https://github.com/opensafety/componentA.git
          git fetch --depth=1 origin ${NEW_SHA}
          git reset ${NEW_SHA}
          cd ${GITHUB_WORKSPACE}
          git status
      - name: Create Pull Request In CompositeA
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Bump ${{ github.repository }} by its merge queue"
          branch: component-mq/main/${{ github.repository }}/${{ github.ref_name }}
          title: "MQ ${{ github.repository }}#${{ github.event.merge_group.id }}"
          body: |
            ${{ format('{{"component_pr":{{"sha":"{0}","repo":"{1}","link":"{2}"}}}}',github.sha,github.repository,'TO_DO') }}
          token: ${{ secrets.ORG_PAT }}
          add-paths: |
            components/componentA
