name: DummyPrActions

on:
  pull_request:

jobs:    
  skipCreatePr:
    name: Create-PR-in-CompositeA
    if: ${{ false }}
    runs-on: ubuntu-22.04    
    steps:
      - name: Print Environment Variables
        run: env | sort
  SkipWaitCompositeA:
    runs-on: ubuntu-22.04    
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.AUTH_APP_ID }}
          private_key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
      - name: 'Dummy: Skip compositeA check'
        uses: LouisBrunner/checks-action@v1.6.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          name: 'CompositeA: Build & Test CompositeA'
          status: completed
          conclusion: neutral
