name: PrintEventData

on:
  push:
  merge_group:
    types:
      - checks_requested
      - destroyed
    branches:
      - main
      - patch*
  pull_request:
  workflow_dispatch:
  check_run:
    types: [created,requested_action, rerequested, completed]
jobs:    
  doPrintEventData:
    runs-on: ubuntu-22.04    
    timeout-minutes: 15
    steps:
      - name: Print GitHub Environment
        run: |
            cat << 'EOF'
            ${{ toJSON(github) }}
            EOF
      - name: Print Environment Variables
        run: env | sort
